<?php
/**
 * @file
 * landlibrary.features.taxonomy.inc
 */

/**
 * Implements hook_taxonomy_default_vocabularies().
 */
function landlibrary_taxonomy_default_vocabularies() {
  return array(
    'format' => array(
      'name' => 'Format',
      'machine_name' => 'format',
      'description' => '',
      'hierarchy' => 0,
      'module' => 'taxonomy',
      'weight' => 0,
      'language' => 'und',
      'i18n_mode' => 1,
      'fc' => array(
        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'entity' => array(
          'vid' => 11,
          'name' => 'Format',
          'machine_name' => 'format',
          'description' => '',
          'hierarchy' => 0,
          'module' => 'taxonomy',
          'weight' => 0,
          'language' => 'und',
          'i18n_mode' => 1,
          'fc' => array(
            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'entity' => array(
              'vid' => 11,
              'name' => 'Format',
              'machine_name' => 'format',
              'description' => '',
              'hierarchy' => 0,
              'module' => 'taxonomy',
              'weight' => 0,
              'language' => 'und',
              'i18n_mode' => 1,
              'fc' => array(
                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'entity' => array(
                  'vid' => 11,
                  'name' => 'Format',
                  'machine_name' => 'format',
                  'description' => '',
                  'hierarchy' => 0,
                  'module' => 'taxonomy',
                  'weight' => 0,
                  'language' => 'und',
                  'i18n_mode' => 1,
                  'fc' => array(
                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'entity' => array(
                      'vid' => 11,
                      'name' => 'Format',
                      'machine_name' => 'format',
                      'description' => '',
                      'hierarchy' => 0,
                      'module' => 'taxonomy',
                      'weight' => 0,
                      'language' => 'und',
                      'i18n_mode' => 1,
                      'fc' => array(
                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'entity' => array(
                          'vid' => 11,
                          'name' => 'Format',
                          'machine_name' => 'format',
                          'description' => '',
                          'hierarchy' => 0,
                          'module' => 'taxonomy',
                          'weight' => 0,
                          'language' => 'und',
                          'i18n_mode' => 1,
                          'fc' => array(
                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'entity' => array(
                              'vid' => 11,
                              'name' => 'Format',
                              'machine_name' => 'format',
                              'description' => '',
                              'hierarchy' => 0,
                              'module' => 'taxonomy',
                              'weight' => 0,
                              'language' => 'und',
                              'i18n_mode' => 1,
                              'fc' => array(
                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                  'vid' => 11,
                                  'name' => 'Format',
                                  'machine_name' => 'format',
                                  'description' => '',
                                  'hierarchy' => 0,
                                  'module' => 'taxonomy',
                                  'weight' => 0,
                                  'language' => 'und',
                                  'i18n_mode' => 1,
                                  'fc' => array(
                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                      'vid' => 11,
                                      'name' => 'Format',
                                      'machine_name' => 'format',
                                      'description' => '',
                                      'hierarchy' => 0,
                                      'module' => 'taxonomy',
                                      'weight' => 0,
                                      'language' => 'und',
                                      'i18n_mode' => 1,
                                      'fc' => array(
                                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'entity' => array(
                                          'vid' => 11,
                                          'name' => 'Format',
                                          'machine_name' => 'format',
                                          'description' => '',
                                          'hierarchy' => 0,
                                          'module' => 'taxonomy',
                                          'weight' => 0,
                                          'language' => 'und',
                                          'i18n_mode' => 1,
                                          'fc' => array(
                                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'entity' => array(
                                              'vid' => 11,
                                              'name' => 'Format',
                                              'machine_name' => 'format',
                                              'description' => '',
                                              'hierarchy' => 0,
                                              'module' => 'taxonomy',
                                              'weight' => 0,
                                              'language' => 'und',
                                              'i18n_mode' => 1,
                                              'fc' => array(
                                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                                  'vid' => 11,
                                                  'name' => 'Format',
                                                  'machine_name' => 'format',
                                                  'description' => '',
                                                  'hierarchy' => 0,
                                                  'module' => 'taxonomy',
                                                  'weight' => 0,
                                                  'language' => 'und',
                                                  'i18n_mode' => 1,
                                                  'fc' => array(
                                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                                      'vid' => ,
                                                      'name' => ,
                                                      'machine_name' => ,
                                                      'description' => ,
                                                      'hierarchy' => ,
                                                      'module' => ,
                                                      'weight' => ,
                                                      'language' => ,
                                                      'i18n_mode' => ,
                                                      'fc' => ,
                                                      'rdf_mapping' => ,
                                                      'field_agrovoc' => ,
                                                    ),
                                                    '' . "\0" . '*' . "\0" . 'id' => 11,
                                                    '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                                  ),
                                                  'rdf_mapping' => array(
                                                    'rdftype' => array(
                                                      0 => 'skos:ConceptScheme',
                                                    ),
                                                    'name' => array(
                                                      'predicates' => array(
                                                        0 => 'dc:title',
                                                      ),
                                                    ),
                                                    'description' => array(
                                                      'predicates' => array(
                                                        0 => 'rdfs:comment',
                                                      ),
                                                    ),
                                                  ),
                                                  'field_agrovoc' => FALSE,
                                                ),
                                                '' . "\0" . '*' . "\0" . 'id' => 11,
                                                '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                              ),
                                              'rdf_mapping' => array(
                                                'rdftype' => array(
                                                  0 => 'skos:ConceptScheme',
                                                ),
                                                'name' => array(
                                                  'predicates' => array(
                                                    0 => 'dc:title',
                                                  ),
                                                ),
                                                'description' => array(
                                                  'predicates' => array(
                                                    0 => 'rdfs:comment',
                                                  ),
                                                ),
                                              ),
                                              'field_agrovoc' => FALSE,
                                            ),
                                            '' . "\0" . '*' . "\0" . 'id' => 11,
                                            '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                          ),
                                          'rdf_mapping' => array(
                                            'rdftype' => array(
                                              0 => 'skos:ConceptScheme',
                                            ),
                                            'name' => array(
                                              'predicates' => array(
                                                0 => 'dc:title',
                                              ),
                                            ),
                                            'description' => array(
                                              'predicates' => array(
                                                0 => 'rdfs:comment',
                                              ),
                                            ),
                                          ),
                                          'field_agrovoc' => FALSE,
                                        ),
                                        '' . "\0" . '*' . "\0" . 'id' => 11,
                                        '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                      ),
                                      'rdf_mapping' => array(
                                        'rdftype' => array(
                                          0 => 'skos:ConceptScheme',
                                        ),
                                        'name' => array(
                                          'predicates' => array(
                                            0 => 'dc:title',
                                          ),
                                        ),
                                        'description' => array(
                                          'predicates' => array(
                                            0 => 'rdfs:comment',
                                          ),
                                        ),
                                      ),
                                      'field_agrovoc' => FALSE,
                                    ),
                                    '' . "\0" . '*' . "\0" . 'id' => 11,
                                    '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                  ),
                                  'rdf_mapping' => array(
                                    'rdftype' => array(
                                      0 => 'skos:ConceptScheme',
                                    ),
                                    'name' => array(
                                      'predicates' => array(
                                        0 => 'dc:title',
                                      ),
                                    ),
                                    'description' => array(
                                      'predicates' => array(
                                        0 => 'rdfs:comment',
                                      ),
                                    ),
                                  ),
                                  'field_agrovoc' => FALSE,
                                ),
                                '' . "\0" . '*' . "\0" . 'id' => 11,
                                '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                              ),
                              'rdf_mapping' => array(
                                'rdftype' => array(
                                  0 => 'skos:ConceptScheme',
                                ),
                                'name' => array(
                                  'predicates' => array(
                                    0 => 'dc:title',
                                  ),
                                ),
                                'description' => array(
                                  'predicates' => array(
                                    0 => 'rdfs:comment',
                                  ),
                                ),
                              ),
                              'field_agrovoc' => FALSE,
                            ),
                            '' . "\0" . '*' . "\0" . 'id' => 11,
                            '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                          ),
                          'rdf_mapping' => array(
                            'rdftype' => array(
                              0 => 'skos:ConceptScheme',
                            ),
                            'name' => array(
                              'predicates' => array(
                                0 => 'dc:title',
                              ),
                            ),
                            'description' => array(
                              'predicates' => array(
                                0 => 'rdfs:comment',
                              ),
                            ),
                          ),
                          'field_agrovoc' => FALSE,
                        ),
                        '' . "\0" . '*' . "\0" . 'id' => 11,
                        '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                      ),
                      'rdf_mapping' => array(
                        'rdftype' => array(
                          0 => 'skos:ConceptScheme',
                        ),
                        'name' => array(
                          'predicates' => array(
                            0 => 'dc:title',
                          ),
                        ),
                        'description' => array(
                          'predicates' => array(
                            0 => 'rdfs:comment',
                          ),
                        ),
                      ),
                      'field_agrovoc' => FALSE,
                    ),
                    '' . "\0" . '*' . "\0" . 'id' => 11,
                    '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                  ),
                  'rdf_mapping' => array(
                    'rdftype' => array(
                      0 => 'skos:ConceptScheme',
                    ),
                    'name' => array(
                      'predicates' => array(
                        0 => 'dc:title',
                      ),
                    ),
                    'description' => array(
                      'predicates' => array(
                        0 => 'rdfs:comment',
                      ),
                    ),
                  ),
                  'field_agrovoc' => FALSE,
                ),
                '' . "\0" . '*' . "\0" . 'id' => 11,
                '' . "\0" . '*' . "\0" . 'revision_id' => 11,
                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                '' . "\0" . '*' . "\0" . 'completeness' => array(),
              ),
              'rdf_mapping' => array(
                'rdftype' => array(
                  0 => 'skos:ConceptScheme',
                ),
                'name' => array(
                  'predicates' => array(
                    0 => 'dc:title',
                  ),
                ),
                'description' => array(
                  'predicates' => array(
                    0 => 'rdfs:comment',
                  ),
                ),
              ),
              'field_agrovoc' => FALSE,
            ),
            '' . "\0" . '*' . "\0" . 'id' => 11,
            '' . "\0" . '*' . "\0" . 'revision_id' => 11,
            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
            '' . "\0" . '*' . "\0" . 'percentage' => 100,
            '' . "\0" . '*' . "\0" . 'completeness' => array(),
          ),
          'rdf_mapping' => array(
            'rdftype' => array(
              0 => 'skos:ConceptScheme',
            ),
            'name' => array(
              'predicates' => array(
                0 => 'dc:title',
              ),
            ),
            'description' => array(
              'predicates' => array(
                0 => 'rdfs:comment',
              ),
            ),
          ),
          'field_agrovoc' => FALSE,
        ),
        '' . "\0" . '*' . "\0" . 'id' => 11,
        '' . "\0" . '*' . "\0" . 'revision_id' => 11,
        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
        '' . "\0" . '*' . "\0" . 'percentage' => 100,
        '' . "\0" . '*' . "\0" . 'completeness' => array(),
      ),
      'rdf_mapping' => array(
        'rdftype' => array(
          0 => 'skos:ConceptScheme',
        ),
        'name' => array(
          'predicates' => array(
            0 => 'dc:title',
          ),
        ),
        'description' => array(
          'predicates' => array(
            0 => 'rdfs:comment',
          ),
        ),
      ),
      'field_agrovoc' => FALSE,
    ),
    'keywords' => array(
      'name' => 'Keywords',
      'machine_name' => 'keywords',
      'description' => '',
      'hierarchy' => 0,
      'module' => 'taxonomy',
      'weight' => 0,
      'language' => 'und',
      'i18n_mode' => 0,
      'fc' => array(
        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'entity' => array(
          'vid' => 13,
          'name' => 'Keywords',
          'machine_name' => 'keywords',
          'description' => '',
          'hierarchy' => 0,
          'module' => 'taxonomy',
          'weight' => 0,
          'language' => 'und',
          'i18n_mode' => 0,
          'fc' => array(
            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'entity' => array(
              'vid' => 13,
              'name' => 'Keywords',
              'machine_name' => 'keywords',
              'description' => '',
              'hierarchy' => 0,
              'module' => 'taxonomy',
              'weight' => 0,
              'language' => 'und',
              'i18n_mode' => 0,
              'fc' => array(
                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'entity' => array(
                  'vid' => 13,
                  'name' => 'Keywords',
                  'machine_name' => 'keywords',
                  'description' => '',
                  'hierarchy' => 0,
                  'module' => 'taxonomy',
                  'weight' => 0,
                  'language' => 'und',
                  'i18n_mode' => 0,
                  'fc' => array(
                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'entity' => array(
                      'vid' => 13,
                      'name' => 'Keywords',
                      'machine_name' => 'keywords',
                      'description' => '',
                      'hierarchy' => 0,
                      'module' => 'taxonomy',
                      'weight' => 0,
                      'language' => 'und',
                      'i18n_mode' => 0,
                      'fc' => array(
                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'entity' => array(
                          'vid' => 13,
                          'name' => 'Keywords',
                          'machine_name' => 'keywords',
                          'description' => '',
                          'hierarchy' => 0,
                          'module' => 'taxonomy',
                          'weight' => 0,
                          'language' => 'und',
                          'i18n_mode' => 0,
                          'fc' => array(
                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'entity' => array(
                              'vid' => 13,
                              'name' => 'Keywords',
                              'machine_name' => 'keywords',
                              'description' => '',
                              'hierarchy' => 0,
                              'module' => 'taxonomy',
                              'weight' => 0,
                              'language' => 'und',
                              'i18n_mode' => 0,
                              'fc' => array(
                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                  'vid' => 13,
                                  'name' => 'Keywords',
                                  'machine_name' => 'keywords',
                                  'description' => '',
                                  'hierarchy' => 0,
                                  'module' => 'taxonomy',
                                  'weight' => 0,
                                  'language' => 'und',
                                  'i18n_mode' => 0,
                                  'fc' => array(
                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                      'vid' => 13,
                                      'name' => 'Keywords',
                                      'machine_name' => 'keywords',
                                      'description' => '',
                                      'hierarchy' => 0,
                                      'module' => 'taxonomy',
                                      'weight' => 0,
                                      'language' => 'und',
                                      'i18n_mode' => 0,
                                      'fc' => array(
                                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'entity' => array(
                                          'vid' => 13,
                                          'name' => 'Keywords',
                                          'machine_name' => 'keywords',
                                          'description' => '',
                                          'hierarchy' => 0,
                                          'module' => 'taxonomy',
                                          'weight' => 0,
                                          'language' => 'und',
                                          'i18n_mode' => 0,
                                          'fc' => array(
                                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'entity' => array(
                                              'vid' => 13,
                                              'name' => 'Keywords',
                                              'machine_name' => 'keywords',
                                              'description' => '',
                                              'hierarchy' => 0,
                                              'module' => 'taxonomy',
                                              'weight' => 0,
                                              'language' => 'und',
                                              'i18n_mode' => 0,
                                              'fc' => array(
                                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                                  'vid' => 13,
                                                  'name' => 'Keywords',
                                                  'machine_name' => 'keywords',
                                                  'description' => '',
                                                  'hierarchy' => 0,
                                                  'module' => 'taxonomy',
                                                  'weight' => 0,
                                                  'language' => 'und',
                                                  'i18n_mode' => 0,
                                                  'fc' => array(
                                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                                      'vid' => ,
                                                      'name' => ,
                                                      'machine_name' => ,
                                                      'description' => ,
                                                      'hierarchy' => ,
                                                      'module' => ,
                                                      'weight' => ,
                                                      'language' => ,
                                                      'i18n_mode' => ,
                                                      'fc' => ,
                                                      'rdf_mapping' => ,
                                                      'field_agrovoc' => ,
                                                    ),
                                                    '' . "\0" . '*' . "\0" . 'id' => 13,
                                                    '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                                  ),
                                                  'rdf_mapping' => array(
                                                    'rdftype' => array(
                                                      0 => 'skos:ConceptScheme',
                                                    ),
                                                    'name' => array(
                                                      'predicates' => array(
                                                        0 => 'dc:title',
                                                      ),
                                                    ),
                                                    'description' => array(
                                                      'predicates' => array(
                                                        0 => 'rdfs:comment',
                                                      ),
                                                    ),
                                                  ),
                                                  'field_agrovoc' => FALSE,
                                                ),
                                                '' . "\0" . '*' . "\0" . 'id' => 13,
                                                '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                              ),
                                              'rdf_mapping' => array(
                                                'rdftype' => array(
                                                  0 => 'skos:ConceptScheme',
                                                ),
                                                'name' => array(
                                                  'predicates' => array(
                                                    0 => 'dc:title',
                                                  ),
                                                ),
                                                'description' => array(
                                                  'predicates' => array(
                                                    0 => 'rdfs:comment',
                                                  ),
                                                ),
                                              ),
                                              'field_agrovoc' => FALSE,
                                            ),
                                            '' . "\0" . '*' . "\0" . 'id' => 13,
                                            '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                          ),
                                          'rdf_mapping' => array(
                                            'rdftype' => array(
                                              0 => 'skos:ConceptScheme',
                                            ),
                                            'name' => array(
                                              'predicates' => array(
                                                0 => 'dc:title',
                                              ),
                                            ),
                                            'description' => array(
                                              'predicates' => array(
                                                0 => 'rdfs:comment',
                                              ),
                                            ),
                                          ),
                                          'field_agrovoc' => FALSE,
                                        ),
                                        '' . "\0" . '*' . "\0" . 'id' => 13,
                                        '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                      ),
                                      'rdf_mapping' => array(
                                        'rdftype' => array(
                                          0 => 'skos:ConceptScheme',
                                        ),
                                        'name' => array(
                                          'predicates' => array(
                                            0 => 'dc:title',
                                          ),
                                        ),
                                        'description' => array(
                                          'predicates' => array(
                                            0 => 'rdfs:comment',
                                          ),
                                        ),
                                      ),
                                      'field_agrovoc' => FALSE,
                                    ),
                                    '' . "\0" . '*' . "\0" . 'id' => 13,
                                    '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                  ),
                                  'rdf_mapping' => array(
                                    'rdftype' => array(
                                      0 => 'skos:ConceptScheme',
                                    ),
                                    'name' => array(
                                      'predicates' => array(
                                        0 => 'dc:title',
                                      ),
                                    ),
                                    'description' => array(
                                      'predicates' => array(
                                        0 => 'rdfs:comment',
                                      ),
                                    ),
                                  ),
                                  'field_agrovoc' => FALSE,
                                ),
                                '' . "\0" . '*' . "\0" . 'id' => 13,
                                '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                              ),
                              'rdf_mapping' => array(
                                'rdftype' => array(
                                  0 => 'skos:ConceptScheme',
                                ),
                                'name' => array(
                                  'predicates' => array(
                                    0 => 'dc:title',
                                  ),
                                ),
                                'description' => array(
                                  'predicates' => array(
                                    0 => 'rdfs:comment',
                                  ),
                                ),
                              ),
                              'field_agrovoc' => FALSE,
                            ),
                            '' . "\0" . '*' . "\0" . 'id' => 13,
                            '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                          ),
                          'rdf_mapping' => array(
                            'rdftype' => array(
                              0 => 'skos:ConceptScheme',
                            ),
                            'name' => array(
                              'predicates' => array(
                                0 => 'dc:title',
                              ),
                            ),
                            'description' => array(
                              'predicates' => array(
                                0 => 'rdfs:comment',
                              ),
                            ),
                          ),
                          'field_agrovoc' => FALSE,
                        ),
                        '' . "\0" . '*' . "\0" . 'id' => 13,
                        '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                      ),
                      'rdf_mapping' => array(
                        'rdftype' => array(
                          0 => 'skos:ConceptScheme',
                        ),
                        'name' => array(
                          'predicates' => array(
                            0 => 'dc:title',
                          ),
                        ),
                        'description' => array(
                          'predicates' => array(
                            0 => 'rdfs:comment',
                          ),
                        ),
                      ),
                      'field_agrovoc' => FALSE,
                    ),
                    '' . "\0" . '*' . "\0" . 'id' => 13,
                    '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                  ),
                  'rdf_mapping' => array(
                    'rdftype' => array(
                      0 => 'skos:ConceptScheme',
                    ),
                    'name' => array(
                      'predicates' => array(
                        0 => 'dc:title',
                      ),
                    ),
                    'description' => array(
                      'predicates' => array(
                        0 => 'rdfs:comment',
                      ),
                    ),
                  ),
                  'field_agrovoc' => FALSE,
                ),
                '' . "\0" . '*' . "\0" . 'id' => 13,
                '' . "\0" . '*' . "\0" . 'revision_id' => 13,
                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                '' . "\0" . '*' . "\0" . 'completeness' => array(),
              ),
              'rdf_mapping' => array(
                'rdftype' => array(
                  0 => 'skos:ConceptScheme',
                ),
                'name' => array(
                  'predicates' => array(
                    0 => 'dc:title',
                  ),
                ),
                'description' => array(
                  'predicates' => array(
                    0 => 'rdfs:comment',
                  ),
                ),
              ),
              'field_agrovoc' => FALSE,
            ),
            '' . "\0" . '*' . "\0" . 'id' => 13,
            '' . "\0" . '*' . "\0" . 'revision_id' => 13,
            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
            '' . "\0" . '*' . "\0" . 'percentage' => 100,
            '' . "\0" . '*' . "\0" . 'completeness' => array(),
          ),
          'rdf_mapping' => array(
            'rdftype' => array(
              0 => 'skos:ConceptScheme',
            ),
            'name' => array(
              'predicates' => array(
                0 => 'dc:title',
              ),
            ),
            'description' => array(
              'predicates' => array(
                0 => 'rdfs:comment',
              ),
            ),
          ),
          'field_agrovoc' => FALSE,
        ),
        '' . "\0" . '*' . "\0" . 'id' => 13,
        '' . "\0" . '*' . "\0" . 'revision_id' => 13,
        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
        '' . "\0" . '*' . "\0" . 'percentage' => 100,
        '' . "\0" . '*' . "\0" . 'completeness' => array(),
      ),
      'rdf_mapping' => array(
        'rdftype' => array(
          0 => 'skos:ConceptScheme',
        ),
        'name' => array(
          'predicates' => array(
            0 => 'dc:title',
          ),
        ),
        'description' => array(
          'predicates' => array(
            0 => 'rdfs:comment',
          ),
        ),
      ),
      'field_agrovoc' => FALSE,
    ),
    'landlibrary_resource_type' => array(
      'name' => 'LandLibrary Resource Type',
      'machine_name' => 'landlibrary_resource_type',
      'description' => '',
      'hierarchy' => 0,
      'module' => 'taxonomy',
      'weight' => 0,
      'language' => 'und',
      'i18n_mode' => 1,
      'fc' => array(
        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'entity' => array(
          'vid' => 9,
          'name' => 'LandLibrary Resource Type',
          'machine_name' => 'landlibrary_resource_type',
          'description' => '',
          'hierarchy' => 0,
          'module' => 'taxonomy',
          'weight' => 0,
          'language' => 'und',
          'i18n_mode' => 1,
          'fc' => array(
            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'entity' => array(
              'vid' => 9,
              'name' => 'LandLibrary Resource Type',
              'machine_name' => 'landlibrary_resource_type',
              'description' => '',
              'hierarchy' => 0,
              'module' => 'taxonomy',
              'weight' => 0,
              'language' => 'und',
              'i18n_mode' => 1,
              'fc' => array(
                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'entity' => array(
                  'vid' => 9,
                  'name' => 'LandLibrary Resource Type',
                  'machine_name' => 'landlibrary_resource_type',
                  'description' => '',
                  'hierarchy' => 0,
                  'module' => 'taxonomy',
                  'weight' => 0,
                  'language' => 'und',
                  'i18n_mode' => 1,
                  'fc' => array(
                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'entity' => array(
                      'vid' => 9,
                      'name' => 'LandLibrary Resource Type',
                      'machine_name' => 'landlibrary_resource_type',
                      'description' => '',
                      'hierarchy' => 0,
                      'module' => 'taxonomy',
                      'weight' => 0,
                      'language' => 'und',
                      'i18n_mode' => 1,
                      'fc' => array(
                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'entity' => array(
                          'vid' => 9,
                          'name' => 'LandLibrary Resource Type',
                          'machine_name' => 'landlibrary_resource_type',
                          'description' => '',
                          'hierarchy' => 0,
                          'module' => 'taxonomy',
                          'weight' => 0,
                          'language' => 'und',
                          'i18n_mode' => 1,
                          'fc' => array(
                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'entity' => array(
                              'vid' => 9,
                              'name' => 'LandLibrary Resource Type',
                              'machine_name' => 'landlibrary_resource_type',
                              'description' => '',
                              'hierarchy' => 0,
                              'module' => 'taxonomy',
                              'weight' => 0,
                              'language' => 'und',
                              'i18n_mode' => 1,
                              'fc' => array(
                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                  'vid' => 9,
                                  'name' => 'LandLibrary Resource Type',
                                  'machine_name' => 'landlibrary_resource_type',
                                  'description' => '',
                                  'hierarchy' => 0,
                                  'module' => 'taxonomy',
                                  'weight' => 0,
                                  'language' => 'und',
                                  'i18n_mode' => 1,
                                  'fc' => array(
                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                      'vid' => 9,
                                      'name' => 'LandLibrary Resource Type',
                                      'machine_name' => 'landlibrary_resource_type',
                                      'description' => '',
                                      'hierarchy' => 0,
                                      'module' => 'taxonomy',
                                      'weight' => 0,
                                      'language' => 'und',
                                      'i18n_mode' => 1,
                                      'fc' => array(
                                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'entity' => array(
                                          'vid' => 9,
                                          'name' => 'LandLibrary Resource Type',
                                          'machine_name' => 'landlibrary_resource_type',
                                          'description' => '',
                                          'hierarchy' => 0,
                                          'module' => 'taxonomy',
                                          'weight' => 0,
                                          'language' => 'und',
                                          'i18n_mode' => 1,
                                          'fc' => array(
                                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'entity' => array(
                                              'vid' => 9,
                                              'name' => 'LandLibrary Resource Type',
                                              'machine_name' => 'landlibrary_resource_type',
                                              'description' => '',
                                              'hierarchy' => 0,
                                              'module' => 'taxonomy',
                                              'weight' => 0,
                                              'language' => 'und',
                                              'i18n_mode' => 1,
                                              'fc' => array(
                                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                                  'vid' => 9,
                                                  'name' => 'LandLibrary Resource Type',
                                                  'machine_name' => 'landlibrary_resource_type',
                                                  'description' => '',
                                                  'hierarchy' => 0,
                                                  'module' => 'taxonomy',
                                                  'weight' => 0,
                                                  'language' => 'und',
                                                  'i18n_mode' => 1,
                                                  'fc' => array(
                                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                                      'vid' => ,
                                                      'name' => ,
                                                      'machine_name' => ,
                                                      'description' => ,
                                                      'hierarchy' => ,
                                                      'module' => ,
                                                      'weight' => ,
                                                      'language' => ,
                                                      'i18n_mode' => ,
                                                      'fc' => ,
                                                      'rdf_mapping' => ,
                                                      'field_agrovoc' => ,
                                                    ),
                                                    '' . "\0" . '*' . "\0" . 'id' => 9,
                                                    '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                                  ),
                                                  'rdf_mapping' => array(
                                                    'rdftype' => array(
                                                      0 => 'skos:ConceptScheme',
                                                    ),
                                                    'name' => array(
                                                      'predicates' => array(
                                                        0 => 'dc:title',
                                                      ),
                                                    ),
                                                    'description' => array(
                                                      'predicates' => array(
                                                        0 => 'rdfs:comment',
                                                      ),
                                                    ),
                                                  ),
                                                  'field_agrovoc' => FALSE,
                                                ),
                                                '' . "\0" . '*' . "\0" . 'id' => 9,
                                                '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                              ),
                                              'rdf_mapping' => array(
                                                'rdftype' => array(
                                                  0 => 'skos:ConceptScheme',
                                                ),
                                                'name' => array(
                                                  'predicates' => array(
                                                    0 => 'dc:title',
                                                  ),
                                                ),
                                                'description' => array(
                                                  'predicates' => array(
                                                    0 => 'rdfs:comment',
                                                  ),
                                                ),
                                              ),
                                              'field_agrovoc' => FALSE,
                                            ),
                                            '' . "\0" . '*' . "\0" . 'id' => 9,
                                            '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                          ),
                                          'rdf_mapping' => array(
                                            'rdftype' => array(
                                              0 => 'skos:ConceptScheme',
                                            ),
                                            'name' => array(
                                              'predicates' => array(
                                                0 => 'dc:title',
                                              ),
                                            ),
                                            'description' => array(
                                              'predicates' => array(
                                                0 => 'rdfs:comment',
                                              ),
                                            ),
                                          ),
                                          'field_agrovoc' => FALSE,
                                        ),
                                        '' . "\0" . '*' . "\0" . 'id' => 9,
                                        '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                      ),
                                      'rdf_mapping' => array(
                                        'rdftype' => array(
                                          0 => 'skos:ConceptScheme',
                                        ),
                                        'name' => array(
                                          'predicates' => array(
                                            0 => 'dc:title',
                                          ),
                                        ),
                                        'description' => array(
                                          'predicates' => array(
                                            0 => 'rdfs:comment',
                                          ),
                                        ),
                                      ),
                                      'field_agrovoc' => FALSE,
                                    ),
                                    '' . "\0" . '*' . "\0" . 'id' => 9,
                                    '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                  ),
                                  'rdf_mapping' => array(
                                    'rdftype' => array(
                                      0 => 'skos:ConceptScheme',
                                    ),
                                    'name' => array(
                                      'predicates' => array(
                                        0 => 'dc:title',
                                      ),
                                    ),
                                    'description' => array(
                                      'predicates' => array(
                                        0 => 'rdfs:comment',
                                      ),
                                    ),
                                  ),
                                  'field_agrovoc' => FALSE,
                                ),
                                '' . "\0" . '*' . "\0" . 'id' => 9,
                                '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                              ),
                              'rdf_mapping' => array(
                                'rdftype' => array(
                                  0 => 'skos:ConceptScheme',
                                ),
                                'name' => array(
                                  'predicates' => array(
                                    0 => 'dc:title',
                                  ),
                                ),
                                'description' => array(
                                  'predicates' => array(
                                    0 => 'rdfs:comment',
                                  ),
                                ),
                              ),
                              'field_agrovoc' => FALSE,
                            ),
                            '' . "\0" . '*' . "\0" . 'id' => 9,
                            '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                          ),
                          'rdf_mapping' => array(
                            'rdftype' => array(
                              0 => 'skos:ConceptScheme',
                            ),
                            'name' => array(
                              'predicates' => array(
                                0 => 'dc:title',
                              ),
                            ),
                            'description' => array(
                              'predicates' => array(
                                0 => 'rdfs:comment',
                              ),
                            ),
                          ),
                          'field_agrovoc' => FALSE,
                        ),
                        '' . "\0" . '*' . "\0" . 'id' => 9,
                        '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                      ),
                      'rdf_mapping' => array(
                        'rdftype' => array(
                          0 => 'skos:ConceptScheme',
                        ),
                        'name' => array(
                          'predicates' => array(
                            0 => 'dc:title',
                          ),
                        ),
                        'description' => array(
                          'predicates' => array(
                            0 => 'rdfs:comment',
                          ),
                        ),
                      ),
                      'field_agrovoc' => FALSE,
                    ),
                    '' . "\0" . '*' . "\0" . 'id' => 9,
                    '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                  ),
                  'rdf_mapping' => array(
                    'rdftype' => array(
                      0 => 'skos:ConceptScheme',
                    ),
                    'name' => array(
                      'predicates' => array(
                        0 => 'dc:title',
                      ),
                    ),
                    'description' => array(
                      'predicates' => array(
                        0 => 'rdfs:comment',
                      ),
                    ),
                  ),
                  'field_agrovoc' => FALSE,
                ),
                '' . "\0" . '*' . "\0" . 'id' => 9,
                '' . "\0" . '*' . "\0" . 'revision_id' => 9,
                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                '' . "\0" . '*' . "\0" . 'completeness' => array(),
              ),
              'rdf_mapping' => array(
                'rdftype' => array(
                  0 => 'skos:ConceptScheme',
                ),
                'name' => array(
                  'predicates' => array(
                    0 => 'dc:title',
                  ),
                ),
                'description' => array(
                  'predicates' => array(
                    0 => 'rdfs:comment',
                  ),
                ),
              ),
              'field_agrovoc' => FALSE,
            ),
            '' . "\0" . '*' . "\0" . 'id' => 9,
            '' . "\0" . '*' . "\0" . 'revision_id' => 9,
            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
            '' . "\0" . '*' . "\0" . 'percentage' => 100,
            '' . "\0" . '*' . "\0" . 'completeness' => array(),
          ),
          'rdf_mapping' => array(
            'rdftype' => array(
              0 => 'skos:ConceptScheme',
            ),
            'name' => array(
              'predicates' => array(
                0 => 'dc:title',
              ),
            ),
            'description' => array(
              'predicates' => array(
                0 => 'rdfs:comment',
              ),
            ),
          ),
          'field_agrovoc' => FALSE,
        ),
        '' . "\0" . '*' . "\0" . 'id' => 9,
        '' . "\0" . '*' . "\0" . 'revision_id' => 9,
        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
        '' . "\0" . '*' . "\0" . 'percentage' => 100,
        '' . "\0" . '*' . "\0" . 'completeness' => array(),
      ),
      'rdf_mapping' => array(
        'rdftype' => array(
          0 => 'skos:ConceptScheme',
        ),
        'name' => array(
          'predicates' => array(
            0 => 'dc:title',
          ),
        ),
        'description' => array(
          'predicates' => array(
            0 => 'rdfs:comment',
          ),
        ),
      ),
      'field_agrovoc' => FALSE,
    ),
    'licences' => array(
      'name' => 'Licences',
      'machine_name' => 'licences',
      'description' => '',
      'hierarchy' => 0,
      'module' => 'taxonomy',
      'weight' => 0,
      'language' => 'und',
      'i18n_mode' => 1,
      'fc' => array(
        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'entity' => array(
          'vid' => 12,
          'name' => 'Licences',
          'machine_name' => 'licences',
          'description' => '',
          'hierarchy' => 0,
          'module' => 'taxonomy',
          'weight' => 0,
          'language' => 'und',
          'i18n_mode' => 1,
          'fc' => array(
            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'entity' => array(
              'vid' => 12,
              'name' => 'Licences',
              'machine_name' => 'licences',
              'description' => '',
              'hierarchy' => 0,
              'module' => 'taxonomy',
              'weight' => 0,
              'language' => 'und',
              'i18n_mode' => 1,
              'fc' => array(
                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'entity' => array(
                  'vid' => 12,
                  'name' => 'Licences',
                  'machine_name' => 'licences',
                  'description' => '',
                  'hierarchy' => 0,
                  'module' => 'taxonomy',
                  'weight' => 0,
                  'language' => 'und',
                  'i18n_mode' => 1,
                  'fc' => array(
                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'entity' => array(
                      'vid' => 12,
                      'name' => 'Licences',
                      'machine_name' => 'licences',
                      'description' => '',
                      'hierarchy' => 0,
                      'module' => 'taxonomy',
                      'weight' => 0,
                      'language' => 'und',
                      'i18n_mode' => 1,
                      'fc' => array(
                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'entity' => array(
                          'vid' => 12,
                          'name' => 'Licences',
                          'machine_name' => 'licences',
                          'description' => '',
                          'hierarchy' => 0,
                          'module' => 'taxonomy',
                          'weight' => 0,
                          'language' => 'und',
                          'i18n_mode' => 1,
                          'fc' => array(
                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'entity' => array(
                              'vid' => 12,
                              'name' => 'Licences',
                              'machine_name' => 'licences',
                              'description' => '',
                              'hierarchy' => 0,
                              'module' => 'taxonomy',
                              'weight' => 0,
                              'language' => 'und',
                              'i18n_mode' => 1,
                              'fc' => array(
                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                  'vid' => 12,
                                  'name' => 'Licences',
                                  'machine_name' => 'licences',
                                  'description' => '',
                                  'hierarchy' => 0,
                                  'module' => 'taxonomy',
                                  'weight' => 0,
                                  'language' => 'und',
                                  'i18n_mode' => 1,
                                  'fc' => array(
                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                      'vid' => 12,
                                      'name' => 'Licences',
                                      'machine_name' => 'licences',
                                      'description' => '',
                                      'hierarchy' => 0,
                                      'module' => 'taxonomy',
                                      'weight' => 0,
                                      'language' => 'und',
                                      'i18n_mode' => 1,
                                      'fc' => array(
                                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'entity' => array(
                                          'vid' => 12,
                                          'name' => 'Licences',
                                          'machine_name' => 'licences',
                                          'description' => '',
                                          'hierarchy' => 0,
                                          'module' => 'taxonomy',
                                          'weight' => 0,
                                          'language' => 'und',
                                          'i18n_mode' => 1,
                                          'fc' => array(
                                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'entity' => array(
                                              'vid' => 12,
                                              'name' => 'Licences',
                                              'machine_name' => 'licences',
                                              'description' => '',
                                              'hierarchy' => 0,
                                              'module' => 'taxonomy',
                                              'weight' => 0,
                                              'language' => 'und',
                                              'i18n_mode' => 1,
                                              'fc' => array(
                                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                                  'vid' => 12,
                                                  'name' => 'Licences',
                                                  'machine_name' => 'licences',
                                                  'description' => '',
                                                  'hierarchy' => 0,
                                                  'module' => 'taxonomy',
                                                  'weight' => 0,
                                                  'language' => 'und',
                                                  'i18n_mode' => 1,
                                                  'fc' => array(
                                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                                      'vid' => ,
                                                      'name' => ,
                                                      'machine_name' => ,
                                                      'description' => ,
                                                      'hierarchy' => ,
                                                      'module' => ,
                                                      'weight' => ,
                                                      'language' => ,
                                                      'i18n_mode' => ,
                                                      'fc' => ,
                                                      'rdf_mapping' => ,
                                                      'field_agrovoc' => ,
                                                    ),
                                                    '' . "\0" . '*' . "\0" . 'id' => 12,
                                                    '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                                  ),
                                                  'rdf_mapping' => array(
                                                    'rdftype' => array(
                                                      0 => 'skos:ConceptScheme',
                                                    ),
                                                    'name' => array(
                                                      'predicates' => array(
                                                        0 => 'dc:title',
                                                      ),
                                                    ),
                                                    'description' => array(
                                                      'predicates' => array(
                                                        0 => 'rdfs:comment',
                                                      ),
                                                    ),
                                                  ),
                                                  'field_agrovoc' => FALSE,
                                                ),
                                                '' . "\0" . '*' . "\0" . 'id' => 12,
                                                '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                              ),
                                              'rdf_mapping' => array(
                                                'rdftype' => array(
                                                  0 => 'skos:ConceptScheme',
                                                ),
                                                'name' => array(
                                                  'predicates' => array(
                                                    0 => 'dc:title',
                                                  ),
                                                ),
                                                'description' => array(
                                                  'predicates' => array(
                                                    0 => 'rdfs:comment',
                                                  ),
                                                ),
                                              ),
                                              'field_agrovoc' => FALSE,
                                            ),
                                            '' . "\0" . '*' . "\0" . 'id' => 12,
                                            '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                          ),
                                          'rdf_mapping' => array(
                                            'rdftype' => array(
                                              0 => 'skos:ConceptScheme',
                                            ),
                                            'name' => array(
                                              'predicates' => array(
                                                0 => 'dc:title',
                                              ),
                                            ),
                                            'description' => array(
                                              'predicates' => array(
                                                0 => 'rdfs:comment',
                                              ),
                                            ),
                                          ),
                                          'field_agrovoc' => FALSE,
                                        ),
                                        '' . "\0" . '*' . "\0" . 'id' => 12,
                                        '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                      ),
                                      'rdf_mapping' => array(
                                        'rdftype' => array(
                                          0 => 'skos:ConceptScheme',
                                        ),
                                        'name' => array(
                                          'predicates' => array(
                                            0 => 'dc:title',
                                          ),
                                        ),
                                        'description' => array(
                                          'predicates' => array(
                                            0 => 'rdfs:comment',
                                          ),
                                        ),
                                      ),
                                      'field_agrovoc' => FALSE,
                                    ),
                                    '' . "\0" . '*' . "\0" . 'id' => 12,
                                    '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                  ),
                                  'rdf_mapping' => array(
                                    'rdftype' => array(
                                      0 => 'skos:ConceptScheme',
                                    ),
                                    'name' => array(
                                      'predicates' => array(
                                        0 => 'dc:title',
                                      ),
                                    ),
                                    'description' => array(
                                      'predicates' => array(
                                        0 => 'rdfs:comment',
                                      ),
                                    ),
                                  ),
                                  'field_agrovoc' => FALSE,
                                ),
                                '' . "\0" . '*' . "\0" . 'id' => 12,
                                '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                              ),
                              'rdf_mapping' => array(
                                'rdftype' => array(
                                  0 => 'skos:ConceptScheme',
                                ),
                                'name' => array(
                                  'predicates' => array(
                                    0 => 'dc:title',
                                  ),
                                ),
                                'description' => array(
                                  'predicates' => array(
                                    0 => 'rdfs:comment',
                                  ),
                                ),
                              ),
                              'field_agrovoc' => FALSE,
                            ),
                            '' . "\0" . '*' . "\0" . 'id' => 12,
                            '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                          ),
                          'rdf_mapping' => array(
                            'rdftype' => array(
                              0 => 'skos:ConceptScheme',
                            ),
                            'name' => array(
                              'predicates' => array(
                                0 => 'dc:title',
                              ),
                            ),
                            'description' => array(
                              'predicates' => array(
                                0 => 'rdfs:comment',
                              ),
                            ),
                          ),
                          'field_agrovoc' => FALSE,
                        ),
                        '' . "\0" . '*' . "\0" . 'id' => 12,
                        '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                      ),
                      'rdf_mapping' => array(
                        'rdftype' => array(
                          0 => 'skos:ConceptScheme',
                        ),
                        'name' => array(
                          'predicates' => array(
                            0 => 'dc:title',
                          ),
                        ),
                        'description' => array(
                          'predicates' => array(
                            0 => 'rdfs:comment',
                          ),
                        ),
                      ),
                      'field_agrovoc' => FALSE,
                    ),
                    '' . "\0" . '*' . "\0" . 'id' => 12,
                    '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                  ),
                  'rdf_mapping' => array(
                    'rdftype' => array(
                      0 => 'skos:ConceptScheme',
                    ),
                    'name' => array(
                      'predicates' => array(
                        0 => 'dc:title',
                      ),
                    ),
                    'description' => array(
                      'predicates' => array(
                        0 => 'rdfs:comment',
                      ),
                    ),
                  ),
                  'field_agrovoc' => FALSE,
                ),
                '' . "\0" . '*' . "\0" . 'id' => 12,
                '' . "\0" . '*' . "\0" . 'revision_id' => 12,
                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                '' . "\0" . '*' . "\0" . 'completeness' => array(),
              ),
              'rdf_mapping' => array(
                'rdftype' => array(
                  0 => 'skos:ConceptScheme',
                ),
                'name' => array(
                  'predicates' => array(
                    0 => 'dc:title',
                  ),
                ),
                'description' => array(
                  'predicates' => array(
                    0 => 'rdfs:comment',
                  ),
                ),
              ),
              'field_agrovoc' => FALSE,
            ),
            '' . "\0" . '*' . "\0" . 'id' => 12,
            '' . "\0" . '*' . "\0" . 'revision_id' => 12,
            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
            '' . "\0" . '*' . "\0" . 'percentage' => 100,
            '' . "\0" . '*' . "\0" . 'completeness' => array(),
          ),
          'rdf_mapping' => array(
            'rdftype' => array(
              0 => 'skos:ConceptScheme',
            ),
            'name' => array(
              'predicates' => array(
                0 => 'dc:title',
              ),
            ),
            'description' => array(
              'predicates' => array(
                0 => 'rdfs:comment',
              ),
            ),
          ),
          'field_agrovoc' => FALSE,
        ),
        '' . "\0" . '*' . "\0" . 'id' => 12,
        '' . "\0" . '*' . "\0" . 'revision_id' => 12,
        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
        '' . "\0" . '*' . "\0" . 'percentage' => 100,
        '' . "\0" . '*' . "\0" . 'completeness' => array(),
      ),
      'rdf_mapping' => array(
        'rdftype' => array(
          0 => 'skos:ConceptScheme',
        ),
        'name' => array(
          'predicates' => array(
            0 => 'dc:title',
          ),
        ),
        'description' => array(
          'predicates' => array(
            0 => 'rdfs:comment',
          ),
        ),
      ),
      'field_agrovoc' => FALSE,
    ),
    'terms_of_use' => array(
      'name' => 'Terms of Use',
      'machine_name' => 'terms_of_use',
      'description' => '',
      'hierarchy' => 0,
      'module' => 'taxonomy',
      'weight' => 0,
      'language' => 'und',
      'i18n_mode' => 1,
      'fc' => array(
        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'entity' => array(
          'vid' => 10,
          'name' => 'Terms of Use',
          'machine_name' => 'terms_of_use',
          'description' => '',
          'hierarchy' => 0,
          'module' => 'taxonomy',
          'weight' => 0,
          'language' => 'und',
          'i18n_mode' => 1,
          'fc' => array(
            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'entity' => array(
              'vid' => 10,
              'name' => 'Terms of Use',
              'machine_name' => 'terms_of_use',
              'description' => '',
              'hierarchy' => 0,
              'module' => 'taxonomy',
              'weight' => 0,
              'language' => 'und',
              'i18n_mode' => 1,
              'fc' => array(
                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'entity' => array(
                  'vid' => 10,
                  'name' => 'Terms of Use',
                  'machine_name' => 'terms_of_use',
                  'description' => '',
                  'hierarchy' => 0,
                  'module' => 'taxonomy',
                  'weight' => 0,
                  'language' => 'und',
                  'i18n_mode' => 1,
                  'fc' => array(
                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'entity' => array(
                      'vid' => 10,
                      'name' => 'Terms of Use',
                      'machine_name' => 'terms_of_use',
                      'description' => '',
                      'hierarchy' => 0,
                      'module' => 'taxonomy',
                      'weight' => 0,
                      'language' => 'und',
                      'i18n_mode' => 1,
                      'fc' => array(
                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'entity' => array(
                          'vid' => 10,
                          'name' => 'Terms of Use',
                          'machine_name' => 'terms_of_use',
                          'description' => '',
                          'hierarchy' => 0,
                          'module' => 'taxonomy',
                          'weight' => 0,
                          'language' => 'und',
                          'i18n_mode' => 1,
                          'fc' => array(
                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'entity' => array(
                              'vid' => 10,
                              'name' => 'Terms of Use',
                              'machine_name' => 'terms_of_use',
                              'description' => '',
                              'hierarchy' => 0,
                              'module' => 'taxonomy',
                              'weight' => 0,
                              'language' => 'und',
                              'i18n_mode' => 1,
                              'fc' => array(
                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                  'vid' => 10,
                                  'name' => 'Terms of Use',
                                  'machine_name' => 'terms_of_use',
                                  'description' => '',
                                  'hierarchy' => 0,
                                  'module' => 'taxonomy',
                                  'weight' => 0,
                                  'language' => 'und',
                                  'i18n_mode' => 1,
                                  'fc' => array(
                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                      'vid' => 10,
                                      'name' => 'Terms of Use',
                                      'machine_name' => 'terms_of_use',
                                      'description' => '',
                                      'hierarchy' => 0,
                                      'module' => 'taxonomy',
                                      'weight' => 0,
                                      'language' => 'und',
                                      'i18n_mode' => 1,
                                      'fc' => array(
                                        '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'entity' => array(
                                          'vid' => 10,
                                          'name' => 'Terms of Use',
                                          'machine_name' => 'terms_of_use',
                                          'description' => '',
                                          'hierarchy' => 0,
                                          'module' => 'taxonomy',
                                          'weight' => 0,
                                          'language' => 'und',
                                          'i18n_mode' => 1,
                                          'fc' => array(
                                            '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'entity' => array(
                                              'vid' => 10,
                                              'name' => 'Terms of Use',
                                              'machine_name' => 'terms_of_use',
                                              'description' => '',
                                              'hierarchy' => 0,
                                              'module' => 'taxonomy',
                                              'weight' => 0,
                                              'language' => 'und',
                                              'i18n_mode' => 1,
                                              'fc' => array(
                                                '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'entity' => array(
                                                  'vid' => 10,
                                                  'name' => 'Terms of Use',
                                                  'machine_name' => 'terms_of_use',
                                                  'description' => '',
                                                  'hierarchy' => 0,
                                                  'module' => 'taxonomy',
                                                  'weight' => 0,
                                                  'language' => 'und',
                                                  'i18n_mode' => 1,
                                                  'fc' => array(
                                                    '' . "\0" . '*' . "\0" . 'entity_type' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'entity' => array(
                                                      'vid' => ,
                                                      'name' => ,
                                                      'machine_name' => ,
                                                      'description' => ,
                                                      'hierarchy' => ,
                                                      'module' => ,
                                                      'weight' => ,
                                                      'language' => ,
                                                      'i18n_mode' => ,
                                                      'fc' => ,
                                                      'rdf_mapping' => ,
                                                      'field_agrovoc' => ,
                                                    ),
                                                    '' . "\0" . '*' . "\0" . 'id' => 10,
                                                    '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                                  ),
                                                  'rdf_mapping' => array(
                                                    'rdftype' => array(
                                                      0 => 'skos:ConceptScheme',
                                                    ),
                                                    'name' => array(
                                                      'predicates' => array(
                                                        0 => 'dc:title',
                                                      ),
                                                    ),
                                                    'description' => array(
                                                      'predicates' => array(
                                                        0 => 'rdfs:comment',
                                                      ),
                                                    ),
                                                  ),
                                                  'field_agrovoc' => FALSE,
                                                ),
                                                '' . "\0" . '*' . "\0" . 'id' => 10,
                                                '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                              ),
                                              'rdf_mapping' => array(
                                                'rdftype' => array(
                                                  0 => 'skos:ConceptScheme',
                                                ),
                                                'name' => array(
                                                  'predicates' => array(
                                                    0 => 'dc:title',
                                                  ),
                                                ),
                                                'description' => array(
                                                  'predicates' => array(
                                                    0 => 'rdfs:comment',
                                                  ),
                                                ),
                                              ),
                                              'field_agrovoc' => FALSE,
                                            ),
                                            '' . "\0" . '*' . "\0" . 'id' => 10,
                                            '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                          ),
                                          'rdf_mapping' => array(
                                            'rdftype' => array(
                                              0 => 'skos:ConceptScheme',
                                            ),
                                            'name' => array(
                                              'predicates' => array(
                                                0 => 'dc:title',
                                              ),
                                            ),
                                            'description' => array(
                                              'predicates' => array(
                                                0 => 'rdfs:comment',
                                              ),
                                            ),
                                          ),
                                          'field_agrovoc' => FALSE,
                                        ),
                                        '' . "\0" . '*' . "\0" . 'id' => 10,
                                        '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                      ),
                                      'rdf_mapping' => array(
                                        'rdftype' => array(
                                          0 => 'skos:ConceptScheme',
                                        ),
                                        'name' => array(
                                          'predicates' => array(
                                            0 => 'dc:title',
                                          ),
                                        ),
                                        'description' => array(
                                          'predicates' => array(
                                            0 => 'rdfs:comment',
                                          ),
                                        ),
                                      ),
                                      'field_agrovoc' => FALSE,
                                    ),
                                    '' . "\0" . '*' . "\0" . 'id' => 10,
                                    '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                                  ),
                                  'rdf_mapping' => array(
                                    'rdftype' => array(
                                      0 => 'skos:ConceptScheme',
                                    ),
                                    'name' => array(
                                      'predicates' => array(
                                        0 => 'dc:title',
                                      ),
                                    ),
                                    'description' => array(
                                      'predicates' => array(
                                        0 => 'rdfs:comment',
                                      ),
                                    ),
                                  ),
                                  'field_agrovoc' => FALSE,
                                ),
                                '' . "\0" . '*' . "\0" . 'id' => 10,
                                '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                                '' . "\0" . '*' . "\0" . 'completeness' => array(),
                              ),
                              'rdf_mapping' => array(
                                'rdftype' => array(
                                  0 => 'skos:ConceptScheme',
                                ),
                                'name' => array(
                                  'predicates' => array(
                                    0 => 'dc:title',
                                  ),
                                ),
                                'description' => array(
                                  'predicates' => array(
                                    0 => 'rdfs:comment',
                                  ),
                                ),
                              ),
                              'field_agrovoc' => FALSE,
                            ),
                            '' . "\0" . '*' . "\0" . 'id' => 10,
                            '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                            '' . "\0" . '*' . "\0" . 'percentage' => 100,
                            '' . "\0" . '*' . "\0" . 'completeness' => array(),
                          ),
                          'rdf_mapping' => array(
                            'rdftype' => array(
                              0 => 'skos:ConceptScheme',
                            ),
                            'name' => array(
                              'predicates' => array(
                                0 => 'dc:title',
                              ),
                            ),
                            'description' => array(
                              'predicates' => array(
                                0 => 'rdfs:comment',
                              ),
                            ),
                          ),
                          'field_agrovoc' => FALSE,
                        ),
                        '' . "\0" . '*' . "\0" . 'id' => 10,
                        '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                        '' . "\0" . '*' . "\0" . 'percentage' => 100,
                        '' . "\0" . '*' . "\0" . 'completeness' => array(),
                      ),
                      'rdf_mapping' => array(
                        'rdftype' => array(
                          0 => 'skos:ConceptScheme',
                        ),
                        'name' => array(
                          'predicates' => array(
                            0 => 'dc:title',
                          ),
                        ),
                        'description' => array(
                          'predicates' => array(
                            0 => 'rdfs:comment',
                          ),
                        ),
                      ),
                      'field_agrovoc' => FALSE,
                    ),
                    '' . "\0" . '*' . "\0" . 'id' => 10,
                    '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                    '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                    '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                    '' . "\0" . '*' . "\0" . 'percentage' => 100,
                    '' . "\0" . '*' . "\0" . 'completeness' => array(),
                  ),
                  'rdf_mapping' => array(
                    'rdftype' => array(
                      0 => 'skos:ConceptScheme',
                    ),
                    'name' => array(
                      'predicates' => array(
                        0 => 'dc:title',
                      ),
                    ),
                    'description' => array(
                      'predicates' => array(
                        0 => 'rdfs:comment',
                      ),
                    ),
                  ),
                  'field_agrovoc' => FALSE,
                ),
                '' . "\0" . '*' . "\0" . 'id' => 10,
                '' . "\0" . '*' . "\0" . 'revision_id' => 10,
                '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
                '' . "\0" . '*' . "\0" . 'complete' => TRUE,
                '' . "\0" . '*' . "\0" . 'percentage' => 100,
                '' . "\0" . '*' . "\0" . 'completeness' => array(),
              ),
              'rdf_mapping' => array(
                'rdftype' => array(
                  0 => 'skos:ConceptScheme',
                ),
                'name' => array(
                  'predicates' => array(
                    0 => 'dc:title',
                  ),
                ),
                'description' => array(
                  'predicates' => array(
                    0 => 'rdfs:comment',
                  ),
                ),
              ),
              'field_agrovoc' => FALSE,
            ),
            '' . "\0" . '*' . "\0" . 'id' => 10,
            '' . "\0" . '*' . "\0" . 'revision_id' => 10,
            '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
            '' . "\0" . '*' . "\0" . 'complete' => TRUE,
            '' . "\0" . '*' . "\0" . 'percentage' => 100,
            '' . "\0" . '*' . "\0" . 'completeness' => array(),
          ),
          'rdf_mapping' => array(
            'rdftype' => array(
              0 => 'skos:ConceptScheme',
            ),
            'name' => array(
              'predicates' => array(
                0 => 'dc:title',
              ),
            ),
            'description' => array(
              'predicates' => array(
                0 => 'rdfs:comment',
              ),
            ),
          ),
          'field_agrovoc' => FALSE,
        ),
        '' . "\0" . '*' . "\0" . 'id' => 10,
        '' . "\0" . '*' . "\0" . 'revision_id' => 10,
        '' . "\0" . '*' . "\0" . 'bundle' => 'taxonomy_vocabulary',
        '' . "\0" . '*' . "\0" . 'complete' => TRUE,
        '' . "\0" . '*' . "\0" . 'percentage' => 100,
        '' . "\0" . '*' . "\0" . 'completeness' => array(),
      ),
      'rdf_mapping' => array(
        'rdftype' => array(
          0 => 'skos:ConceptScheme',
        ),
        'name' => array(
          'predicates' => array(
            0 => 'dc:title',
          ),
        ),
        'description' => array(
          'predicates' => array(
            0 => 'rdfs:comment',
          ),
        ),
      ),
      'field_agrovoc' => FALSE,
    ),
  );
}
