<?php
// $Id$




/** gpap
 * Implements hook_apachesolr_index_document_build_entity()
 */
function apachesolr_descr_apachesolr_index_document_build(ApacheSolrDocument $document, $entity,$entity_type, $env_id) {
	$descr = $entity->Description_doc;
   $document->addField('ms_field_doc_description', $descr);
}


function apachesolr_descr_form_apachesolr_query_alter($query) {
  $query->addParam('fl', 'ms_field_doc_description');
  // $query->addParam('sort', 'ms_field_doc_description asc'); 
}
function apachesolr_descr_update_index($document, $node, $namespace) {
 // When indexing nodes, add field from my custom content type
  if ($node->type == 'landlibrary_resource') {
    // grab the image URL and the description
   // $image_uri = $node->field_image['und'][0]['uri'];
    $description = $node->field_doc_description['und'][0]['safe_value'];
    // add the image and description to the document in the solr index
   // $document->addField('ss_my_contenttype_image', $image_uri);
    $document->addField('ms_field_doc_description', $description);
  }
}
